/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __FStar_H
#define __FStar_H



#include "DafnyLib.h"

typedef void *FStar_Pervasives_ex_pre;

extern Prims_int FStar_Int_logand(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_logxor(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_logor(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_lognot(Prims_pos x0, Prims_int x1);

extern Prims_int FStar_Int_shift_right(Prims_pos x0, Prims_int x1, Prims_nat x2);

typedef struct 
{
  uint64_t low;
  uint64_t high;
}
FStar_UInt128_uint128;

typedef FStar_UInt128_uint128 FStar_UInt128_t;

extern void FStar_UInt128_constant_time_carry_ok(uint64_t x0, uint64_t x1);
#endif
