/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library AESEncryptBE_win extracted/AESEncryptBE_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __AESEncryptBE_win_H
#define __AESEncryptBE_win_H




extern void
AESEncryptBE_win_aes128_encrypt_block_be_win(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __AESEncryptBE_win_H_DEFINED
#endif
