/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library AESEncryptBlock AESEncryptBlock.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __AESEncryptBlock_H
#define __AESEncryptBlock_H




extern void AESEncryptBlock_aes128_encrypt_block(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __AESEncryptBlock_H_DEFINED
#endif
