/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library AESEncryptBlock_win extracted/AESEncryptBlock_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __AESEncryptBlock_win_H
#define __AESEncryptBlock_win_H




extern void
AESEncryptBlock_win_aes128_encrypt_block_win(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __AESEncryptBlock_win_H_DEFINED
#endif
