/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library AESEncryptBE AESEncryptBE.krml
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __AESEncryptBE_H
#define __AESEncryptBE_H




extern void AESEncryptBE_aes128_encrypt_block_be(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __AESEncryptBE_H_DEFINED
#endif
