/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Quad32_xor extracted/Quad32_xor.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __C_Loops_Spec_Loops_H
#define __C_Loops_Spec_Loops_H

#include "Quad32_xor.h"
#include "LowStar.h"
#include "FStar.h"
#include "Prims.h"




#define __C_Loops_Spec_Loops_H_DEFINED
#endif
