/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Quad32_xor extracted/Quad32_xor.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __FStar_H
#define __FStar_H

#include "Quad32_xor.h"
#include "LowStar.h"




#define __FStar_H_DEFINED
#endif
