/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_load_xor extracted/Gcm_load_xor.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Gcm_load_xor_H
#define __Gcm_load_xor_H




extern void
Gcm_load_xor_gcm_load_xor_store_buffer(uint8_t *x0, uint8_t *x1, uint8_t *x2, uint64_t x3);

#define __Gcm_load_xor_H_DEFINED
#endif
