/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_make_length extracted/Gcm_make_length.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Gcm_make_length_H
#define __Gcm_make_length_H




extern void Gcm_make_length_gcm_make_length_quad_buffer(uint64_t x0, uint64_t x1, uint8_t *x2);

#define __Gcm_make_length_H_DEFINED
#endif
