/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_make_length extracted/Gcm_make_length.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "Gcm_make_length.h"



