/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_load_xor_win extracted/Gcm_load_xor_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Gcm_load_xor_win_H
#define __Gcm_load_xor_win_H




extern void
Gcm_load_xor_win_gcm_load_xor_store_buffer_win(
  uint8_t *x0,
  uint8_t *x1,
  uint8_t *x2,
  uint64_t x3
);

#define __Gcm_load_xor_win_H_DEFINED
#endif
