/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_load_xor_win extracted/Gcm_load_xor_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "Gcm_load_xor_win.h"



