/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Gcm_make_length_win extracted/Gcm_make_length_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Gcm_make_length_win_H
#define __Gcm_make_length_win_H




extern void
Gcm_make_length_win_gcm_make_length_quad_buffer_win(uint64_t x0, uint64_t x1, uint8_t *x2);

#define __Gcm_make_length_win_H_DEFINED
#endif
