/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GCMEncrypt GCMEncrypt.krml
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GCMEncrypt_H
#define __GCMEncrypt_H




extern void
GCMEncrypt_gcmencrypt(
  uint8_t *x0,
  uint64_t x1,
  uint8_t *x2,
  uint64_t x3,
  uint8_t *x4,
  uint8_t *x5,
  uint8_t *x6,
  uint8_t *x7
);

#define __GCMEncrypt_H_DEFINED
#endif
