/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GCMEncrypt GCMEncrypt.krml
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "GCMEncrypt.h"



