/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GCTR_win extracted/GCTR_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GCTR_win_H
#define __GCTR_win_H




extern void
GCTR_win_gctr_bytes_extra_buffer_win(
  uint8_t *x0,
  uint64_t x1,
  uint8_t *x2,
  uint8_t *x3,
  uint8_t *x4
);

#define __GCTR_win_H_DEFINED
#endif
