/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GCTR extracted/GCTR.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GCTR_H
#define __GCTR_H




extern void
GCTR_gctr_bytes_extra_buffer(uint8_t *x0, uint32_t x1, uint8_t *x2, uint8_t *x3, uint8_t *x4);

#define __GCTR_H_DEFINED
#endif
