/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GCTR_win extracted/GCTR_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "GCTR_win.h"



