/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GHash_one_block extracted/GHash_one_block.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GHash_one_block_H
#define __GHash_one_block_H




extern void
GHash_one_block_ghash_incremental_one_block_buffer(
  uint8_t *x0,
  uint8_t *x1,
  uint8_t *x2,
  uint64_t x3
);

#define __GHash_one_block_H_DEFINED
#endif
