/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GHash_stdcall extracted/GHash_stdcall.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GHash_stdcall_H
#define __GHash_stdcall_H




extern void
GHash_stdcall_ghash_incremental_bytes_stdcall(
  uint8_t *x0,
  uint8_t *x1,
  uint8_t *x2,
  uint64_t x3
);

#define __GHash_stdcall_H_DEFINED
#endif
