/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GHash_extra_win extracted/GHash_extra_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "GHash_extra_win.h"



