/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GHash_extra extracted/GHash_extra.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GHash_extra_H
#define __GHash_extra_H




extern void
GHash_extra_ghash_incremental_extra_stdcall(uint8_t *x0, uint8_t *x1, uint8_t *x2, uint64_t x3);

#define __GHash_extra_H_DEFINED
#endif
