/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library GHash_stdcall_win extracted/GHash_stdcall_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __GHash_stdcall_win_H
#define __GHash_stdcall_win_H




extern void
GHash_stdcall_win_ghash_incremental_bytes_stdcall_win(
  uint8_t *x0,
  uint8_t *x1,
  uint8_t *x2,
  uint64_t x3
);

#define __GHash_stdcall_win_H_DEFINED
#endif
