/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Inc32_win extracted/Inc32_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Inc32_win_H
#define __Inc32_win_H




extern void Inc32_win_inc32_buffer_win(uint8_t *x0);

#define __Inc32_win_H_DEFINED
#endif
