/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Inc32 extracted/Inc32.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Inc32_H
#define __Inc32_H




extern void Inc32_inc32_buffer(uint8_t *x0);

#define __Inc32_H_DEFINED
#endif
