/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Mk_quad32_1 extracted/Mk_quad32_1.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Mk_quad32_1_H
#define __Mk_quad32_1_H




extern void Mk_quad32_1_mk_quad32_lo0_be_1_buffer(uint8_t *x0);

#define __Mk_quad32_1_H_DEFINED
#endif
