/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Mk_quad32_1_win extracted/Mk_quad32_1_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "Mk_quad32_1_win.h"



