/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Mk_quad32_1 extracted/Mk_quad32_1.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "Mk_quad32_1.h"



