/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Mk_quad32_1_win extracted/Mk_quad32_1_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Mk_quad32_1_win_H
#define __Mk_quad32_1_win_H




extern void Mk_quad32_1_win_mk_quad32_lo0_be_1_buffer_win(uint8_t *x0);

#define __Mk_quad32_1_win_H_DEFINED
#endif
