/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Quad32_xor extracted/Quad32_xor.krml -tmpdir extracted/
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Quad32_xor_H
#define __Quad32_xor_H




extern void Quad32_xor_quad32_xor_buffer(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __Quad32_xor_H_DEFINED
#endif
