/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Quad32_xor_win extracted/Quad32_xor_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Quad32_xor_win_H
#define __Quad32_xor_win_H




extern void Quad32_xor_win_quad32_xor_buffer_win(uint8_t *x0, uint8_t *x1, uint8_t *x2);

#define __Quad32_xor_win_H_DEFINED
#endif
