/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Zero_quad32_win extracted/Zero_quad32_win.krml -tmpdir extracted/
 * F* version: 2634db3e
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Zero_quad32_win_H
#define __Zero_quad32_win_H




typedef uint8_t *Zero_quad32_win_b8;

extern void Zero_quad32_win_zero_quad32_buffer(uint8_t *x0);

#define __Zero_quad32_win_H_DEFINED
#endif
