/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Zero_quad32 Zero_quad32.krml
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "kremlib.h"
#ifndef __Zero_quad32_H
#define __Zero_quad32_H




extern void Zero_quad32_zero_quad32_buffer(uint8_t *x0);

#define __Zero_quad32_H_DEFINED
#endif
