/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -library Zero_quad32 Zero_quad32.krml
 * F* version: a5e3f103
 * KreMLin version: d5afab72
 */

#include "Zero_quad32.h"



